### ISSUE TITLE
Compatibility for THREE.js r118

### ISSUE THREAD

**Issue by ferrari212** [shiplab/vesseljs#130]
Our version of vessel is based on the version of THREE.js r86, consequently I noticed some issues about inporting a glb file throught this version and  I had to use a newer version of THREE.js for it. Another problem I wish to report is `Ship3D.js` can not import STL throught the observable, just the version `Ship3D_v2.js`. Those excess of duplicated codes, the disclosere from the currently versions of THREE.js and the use of incompatible functions can make us losing some currently features in THREE.js. Summed to that we have the willing to modernize our code to adequate to ES6 as stated in #103 .

I am currently verifing this compatibility as shown in #128 and I manage to do some alterations in the main features we currently have to support this change:

- The `Configurable_ocean2.js` was created to substitute `Configurable_ocean.js`. The function ocean in this new version eliminate the THREE.Mirror dependency and is based in the [Water.js](https://github.com/mrdoob/three.js/blob/r118/examples/js/objects/Water.js ) instead of [Mirror](https://github.com/shiplab/vesseljs/blob/dev/examples/libs/Mirror.js) according to the example provided in [webgl_shaders_ocean.html](https://github.com/mrdoob/three.js/blob/master/examples/webgl_shaders_ocean.html). We must as well compatibilize with the several versions of oceans as discussed in #129 to ensure no dependency;
- The `skybox_from_example.js` can be substituted by `skybox_from_example_r118.js` when using the r118 from three.js.

The bad pointing about adopting this changes is I am not completly aware how it can effect the dynamical oceans yet and the extra effort necessary to adequate the several examples we have in our main page. I raised this issue to question what we can make in front of it, but for me, keeping increasing the several duplicated snippets and libs will make our library harder and harder to use.

**Comment by icarofonseca** [comment]
I tried to implement an approach where the updated scripts are in the `3D_engine` folder and the older stuff is in the `legacy` subfolder. Older examples invoke the legacy scripts so they can continue working as always. I agree that we should try to clean up the code, but I think we should focus on the main library and build. I suggest that we do not update examples, in order to avoid maintenance workload (in the same way that D3 does not update all the examples when new versions of the library are released). Specially because the number of examples will always be growing in the future and they are developed by students with different skill levels, so I anticipate it would be very demanding to improve all apps to the same quality baseline. In the future, if anyone needs to extend one of the older examples based on legacy scripts, they might update it to work with the newest code base on a need basis.

**Comment by ferrari212** [comment]
Issue closed, compatibility with the THREE.js r118 concluded successfully.
