### ISSUE TITLE
Fix weight on GZ curve and calculate list and trim

### ISSUE THREAD

**Issue by hmgaspar** [shiplab/vesseljs#22]

**Comment by hmgaspar** [comment]
If too difficult, use your cheating (deadline: Xmas)

**Comment by MrEranwe** [comment]
Hi, 

I've added the GZ calculations by hand. It is compared to the Maxsurf GZ curve. 
The hand values are right, I've checked it graphically with AutoCad, so probably there is an error in the assumptions. 

The code is commented, but the assumption is that the area that goes outside of the water should be the same as the area that goes in, since the mass distribution in the hull is the same. When the areas are equal, it calculates the perpendicular to the waterline in that point and then, the perpendicular line again that passes through Keel (0,0). 

I'll keep looking when I finish the last exam next week.

**Comment by EliasHasle** [comment]
Honestly, I think this GZ curve calculation belongs in the shiplab trials, not vesseljs, because it is not very integrated with anything in the library. I would suggest factoring out the contents of the outer loop to a GZ function, for clarity and generality. And solving the piecewise linear equation analytically, instead of guessing tens of thousands of different values.

**Comment by hmgaspar** [comment]
Closing - we can always open a new when this is priority again.
