### ISSUE TITLE
Clickable objects in  3d, with editable info in the GUI

### ISSUE THREAD

**Issue by hmgaspar** [shiplab/vesseljs#56]
Let the user click an object, and show basic info of this object in the GUI control (id, l, b, d, file3D, colors)

**Comment by hmgaspar** [comment]
Is this working? If so, can we have a simple example? @EliasHasle

**Comment by EliasHasle** [comment]
Not now. The `ObjectMenu` that I defined in the conflicting branch outlines how to do a GUI that can switch target. Object picking is typically done by casting a ray from the camera through the mouse pointer with `THREE.Raycaster`. Since multiple objects may intersect the ray, one may need a way to cycle between them, e.g. `tab` or mouse wheel. Or use picking only in a deck-wise 2D view.

You are welcome to use and improve the `ObjectMenu`.

**Comment by hmgaspar** [comment]
Thanks! I'll close the issue for now!
