### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by hmgaspar** [shiplab/vesseljs#9]
Simple API page with some descriptions and/or examples.

**Comment by icarofonseca** [comment]
Also, expand Examples page to document new stability html.

**Comment by icarofonseca** [comment]
Preliminary version of API documentation finished, should be improved by other members.

**Comment by icarofonseca** [comment]
Preliminary version of Ship Stability Calculation example finished. Should be updated in the future for final version of the app.

**Comment by icarofonseca** [comment]
Restructure API page according to Elias' suggestions (break classes in different headers).

**Comment by icarofonseca** [comment]
Debug Hull Hydrostatics example and document it with a tutorial.

**Comment by icarofonseca** [comment]
@EliasHasle, as to the [`ship.calculateStability()`](https://github.com/shiplab/vesseljs/blob/master/source/CoreClasses/Ship.js#L90) method, how can I force it to calculate stability parameters for a given draft chosen by the user, instead of using the draft derived from weight equilibrium calculations inside the [`calculateDraft(shipState, epsilon=0.001)`](https://github.com/shiplab/vesseljs/blob/master/source/CoreClasses/Ship.js#L86) method?

**Comment by icarofonseca** [comment]
In addition, is it ok to push example commits directly to the master branch? This will make them accessible through https://shiplab.github.io/vesseljs/ right away, as the dev branch can't be reached from there.

**Comment by EliasHasle** [comment]
Good questions. I take the last one first. It is OK that you push commits for your own examples to the master branch, if you know what you are doing. :-) It will not be too hard to merge later.

_Ship.prototype.calculateStability_ depends on both draft and weight, and draft depends on weight (and hull geometry). So having draft as a parameter would be misleading. We could possibly have weight (or "displacement") as a parameter, though, instead of the full ship state. The same goes for _calculateDraft_. I think that is cleaner, as none of those methods _need to know_ more. But then, actually, we could have them in the hull class. I think that might be the way to go. (It could even make proper caching easier.)

What is your use case for inputting draft to _Ship.prototype.calculateStability_?

**Comment by icarofonseca** [comment]
I am working on [this example](https://shiplab.github.io/vesseljs/examples/Hull_hydrostatics.html). The idea is to display some hydrostatic properties as functions of the draft, which should be controlled by the user with the gui slider on the page.

**Comment by EliasHasle** [comment]
Right. But the stability calculations are not functions of draft alone.
(Unlike the hull calculations, that take draft as the only external
parameter.)

2017-11-11 20:24 GMT+01:00 Ícaro Fonseca <notifications@github.com>:

**Comment by icarofonseca** [comment]
Yes, I understand. That's why the intention was to display only KB and BM, which depend on the submerged volume but not on the position of the center of gravity (as GM does). In that sense, they could be calculated as functions of the draft only.

**Comment by EliasHasle** [comment]
Oh, then KB and BM could easily be added to the output of
Hull.prototype.calculateAttributesAtDraft(T). KB is already there, in Cv.z,
but we could add an additional reference called KB too. BML and BMT are
calculated from the Iywp and Ixwp values and the submerged volume, so they
can be made there too. I would, however, like to wait until I see what
@MrEranwe says about the modified stability calculations, before moving
some of them to the hull calculation.

2017-11-13 14:45 GMT+01:00 Ícaro Fonseca <notifications@github.com>:

**Comment by icarofonseca** [comment]
Ok, so from the information you provided, I was able to get everything I needed from the outputs of calculateAttributesAtDraft(T): KB, BMl, BMt, LCB and LCF (https://github.com/shiplab/vesseljs/blob/master/examples/Hull_hydrostatics.html#L274). Maybe you'll still want to present those values with their hydrostatic names inside the method just to use familiar terminology to naval architects.

**Comment by EliasHasle** [comment]
Yes, and move the calculation of BMl and BMt there.

I believe LCF is the longitudinal center of the waterplane, or "xcwp" in
the method. You are probably right that it should be changed, or added.

You are welcome to make some careful changes to this on the dev branch, if
you like.

2017-11-14 11:28 GMT+01:00 Ícaro Fonseca <notifications@github.com>:

**Comment by icarofonseca** [comment]
Ok, so I'll do it this week or the next. When I update it, should I deprecate the properties with the current terminology (Cv, xcwp, etc.) or should I leave them there? I wonder if removing them could cause incompatibilities.

**Comment by EliasHasle** [comment]
No, just keep them there for now. It is good to have Cv as a vector for
some calculations. Maybe it should have a more descriptive name, though. If
we define operations for two-dimensional vectors later (it will mostly be a
matter of adjusting the existing vector functions), we can collect xcwp and
ycwp in a vector too (CF or something).

2017-11-15 12:54 GMT+01:00 Ícaro Fonseca <notifications@github.com>:

**Comment by hmgaspar** [comment]
@icarofonseca We shoukd have a "manual" for new examples, given that every year we expect to have students creating new examples. Let's talk about it on the october meeting. I'm closing it for now.
